spdr <- read.table("/apps/fafa/github/eSTAR/scripts/holdings_spdr.dat",sep="\t")
colnames(spdr)=c("Name","ETFName")
library("RPostgreSQL")
mydb<-dbConnect(dbDriver("PostgreSQL"),user='sfdbo',password='sfdbo0',host='localhost',dbname='eSTAR')
dbWriteTable(mydb, "holdings_spdr", spdr, row.names=F, append=F,overwrite=T)
